version: '3.8'

services:
  knp-backend:
    build: .
    container_name: knp-backend
    ports:
      - '5000:5000'
    restart: always
    volumes:
      - ./.env:/knp_backend/.env
      - ./sub.conf:/knp_backend/sub.conf
      - ./panel.conf:/knp_backend/panel.conf
      - ./backup_config.json:/knp_backend/backup_config.json
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - mongo-knp
      - redis-knp
#----------------------------------------------------#
  knp-frontend:
    build: ./frontend
    container_name: knp-frontend
    ports:
      - '3000:3000'
    restart: always
#----------------------------------------------------#
  mongo-knp:
    image: mongo:latest
    container_name: mongo-knp
    volumes:
      - ./docker_volumes/mongodb_data:/data/db
#----------------------------------------------------#
  redis-knp:
    image: redis:latest
    container_name: redis-knp
    volumes:
      - ./docker_volumes/redis_data:/data
#----------------------------------------------------#
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./sub.conf:/etc/nginx/conf.d/sub.conf
      - ./panel.conf:/etc/nginx/conf.d/panel.conf
    ports:
      - "8085:80"
      - "443:443"
    depends_on:
      - knp-backend
